### ISSUE TITLE
async middleware

### ISSUE THREAD

**Issue by fikrivoxel** [lionix-team/vue-route-middleware#4]
Hello,

i have issue with async middleware

case:
first middleware is async and that first middleware not complete and call second sync middlware

![image](https://user-images.githubusercontent.com/54853868/103871692-f90a0c80-50ff-11eb-98b4-80b6b2093687.png)

sorry for mybad english

**Comment by vaawebdev** [comment]
@fikrivoxel The problem is that the middleware invoke is async and we cannot make Vue router to wait for our middleware stack.
Please refer to this comment https://github.com/lionix-team/vue-route-middleware/issues/3#issuecomment-687167020. We got a similar issue but vise versa. If you can solve this issue we are open for a PR.
